import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "@next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";
import DonateHeader from "@/components/Header/DonateHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

// Define Verveine (Local Font)
const verveine = localFont({
  src: "./fonts/VerveineRegular2.ttf", // Path relative to /app directory
  variable: "--font-verveine",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} ${verveine.variable} antialiased`}
      >
        <DonateHeader />
        <Header />
        {children}
      </body>
    </html>
  );
}
